### ISSUE TITLE
Flaky tests with HashcodeAndEqualsCheck and java.util.Date

### ISSUE THREAD

**Issue by Santobert** [Mixermachine/base-test#66]
I noticed flaky tests with objects that have `java.util.Date()` attributes. The HashcodeAndEqualsCheck fails sometimes. Maybe because the default `new Date()` doesn't always produce equal instances.

**Comment by Santobert** [comment]
I could solve this by using the following TestDataProvier. 
Maybe the library should warn about using Date without a TestDataProvider.

```java
TestDataProvider provider = TestDataProvider.getSeededTestDataProvider();
Map<String, Function<String, Object>> map = Map.of(Date.class.getName(), x -> new Date(x.hashCode()));
provider.addCustomMappings(map);
```

**Comment by Mixermachine** [comment]
Hy @Santobert 
Sorry for my later answer. I'm currently loaded with my master thesis.
The next release will contain at least a message, maybe more.
Thanks for writing this 👍

**Comment by Mixermachine** [comment]
Hy @Santobert ,

I already handled Instant correctly but not Date.
https://github.com/Mixermachine/base-test/blob/70f4518d664db27ef275cdcb820d5d49352d9a1c/src/main/java/de/a9d3/testing/testdata/TestDataStatics.java#L83

The line below handles Date now.
Thanks for reporting. It's fixed now and will be delivered with the next release.
